### PR TITLE
fix: cordova androidx build [SI-869]

### PR DESCRIPTION
**Pull request by samvimes01**
to fix `android.support.v7` errors on Capacitor

Should be merged after capacitor migration

https://github.com/Telerik-Verified-Plugins/ImagePicker/issues/236
https://github.com/ionic-team/capacitor/issues/2289

### CODE REVIEW

**Comment by quentin-tardivon** [comment]
I think I missed a step here... Why is this fix targeting master? 🤔

**Comment by samvimes01** [comment]
@quentin-tardivon - this is an ImagePicker library fork. We don't need a special capacitor branch here
What branch should it be targeting?

**Comment by quentin-tardivon** [comment]
> @quentin-tardivon - this is an ImagePicker library fork. We don't need a special capacitor branch here
> What branch should it be targeting?

Yes sorry, I didn't paid attention to the repo 🤭

**Review by quentin-tardivon — APPROVED** [review]
👍

**Review by ArnaudSpanneut — APPROVED** [review]
It would be safer to create versions of this repo and use them in the mobile project to avoid this kind of situation

**Comment by pintojeremy** [comment]
Since I'll add `jetifier` to our `postinstall` step, we may not need this fork anymore.

**Comment by pintojeremy** [comment]
`jetifier` has been added. This PR may be obsolete

**Comment by samvimes01** [comment]
Closing it since we use Jetifier for File opener, but it fixes paths everywhere

**Pull request closed without merging**
